apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  POSTGRES_DB: dmliZTNk   # "vibe3d" em base64
  POSTGRES_USER: dmliZTNkVXNlcg==   # "vibe3dUser" em base64
  POSTGRES_PASSWORD: dmliZTNkUGFzcw==   # "vibe3dPass" em base64